development:
  adapter: postgresql
  encoding: unicode
  database: mom_development
  pool: 5
  username: postgres
  password: kty123
test:
  adapter: postgresql
  encoding: unicode
  database: mom_test
  pool: 5
  username: postgres
  password: kty123

production:
  adapter: postgresql
  encoding: unicode
  database: mom_production
  pool: 5
  username: postgres
  password: kty123
